### ISSUE TITLE
bin/console debug:event-dispatcher is not working

### ISSUE THREAD

**Issue by bartdens** [exesser/exess-skeleton#36]
**Version(s) affected**: all

**Description**  

This command os not working, it outputs:

`[ERROR] Event dispatcher "event_dispatcher" is not available.`

**Steps to reproduce**  

bin/console debug:event-dispatcher

**Comment by kristofvc** [comment]
Indeed we don't use the regular symfony event_dispatcher yet but the custom one we implemented to use with slim. I suspect we need to do some refactoring for this

**Comment by kristofvc** [comment]
@devartbvba Cannot reproduce, might be a wrongly cached container in your case?

**Comment by kristofvc** [comment]
Was accidentally fixed by updating composer and getting our versions in line!
